# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2024-2026 Andrew Rechnitzer

# bundle 1
[[bundles]]
first_paper = 1
last_paper = 25
# bundle 2
[[bundles]]
first_paper = 26
last_paper = 50
# bundle 3
[[bundles]]
first_paper = 51
last_paper = 100
# bundle 4
[[bundles]]
first_paper = 101
last_paper = 150
# bundle 5
[[bundles]]
first_paper = 151
last_paper = 200

# HW bundle 1
[[hw_bundles]]
paper_number = 241
student_id = 98989898
student_name = "Kenson, Ken"
pages = [[1], [2], [], [2, 3], [3], [3,4]]
