# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2023 Edith Coates
# Copyright (C) 2023-2026 Colin B. Macdonald
# Copyright (C) 2024-2026 Andrew Rechnitzer
# Copyright (C) 2024 Bryan Tanady

# bundle 1
[[bundles]]
first_paper = 1
last_paper = 10

# bundle 2
[[bundles]]
first_paper = 11
last_paper = 20
garbage_page_papers = [11, 12]
duplicate_qr_papers = [13, 14]
wrong_version_papers = [15, 16]
duplicate_page_papers = [17, 18]
scrap_page_papers = [17, 18]
wrong_assessment_papers = [11, 12]
out_of_range_papers = [15]
obscure_qr_papers = [11, 12, 13, 14, 15]
invalid_qr_papers = [16, 17]
operations = ["tear", "fold", "rotate", "compress", "lighten"]


# bundle 3
[[bundles]]
first_paper = 21
last_paper = 30
extra_page_papers = [29, 30]
scrap_page_papers = [29, 30]
discard_pages = [51, 54, 60, 64]  # TODO: does this get used by anything?
obscure_qr_papers = [21, 22, 23, 24, 25, 26]
operations = ["darken", "jam", "stretch", "hide", "corrupt", "obscure"]


# bundle 4
[[bundles]]
first_paper = 31
last_paper = 40


# bundle 5
[[bundles]]
first_paper = 41
last_paper = 50
extra_page_papers = [41, 42]
wrong_assessment_papers = [49, 50]
out_of_range_papers = [45]


# HW bundle 1
[[hw_bundles]]
paper_number = 61
student_id = 98989898
student_name = "Kenson, Ken"
pages = [[1], [2], [], [2, 3], [3], [4]]


# HW bundle 2
[[hw_bundles]]
paper_number = 62
student_id = 97979797
student_name = "Lawrence, Larry"
pages = [[1], [1, 2], [2], [], [3], [3,4]]


# HW bundle 3
[[hw_bundles]]
paper_number = 63
student_id = 94949494
student_name = "Nowra, Nora"
pages = [[1, 2], [3], [], [4]]

