# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2024-2025 Colin B. Macdonald
# Copyright (C) 2024-2026 Andrew Rechnitzer
# Copyright (C) 2025 Aidan Murphy

[[rubric]]
kind = "relative"
value = 2
text = "correct limit"
tags = "demo"
meta = "Student evaluated limit correctly"
question_index = 1
username = "manager"

[[rubric]]
kind = "relative"
value = 1
text = "right idea, but be careful"
tags = "demo"
meta = "Student made small arithmetic mistake when computing limit"
question_index = 1
username = "manager"

[[rubric]]
kind = "relative"
value = -2
text = "substantial error"
tags = "demo"
meta = "Student made substantial error when computing limit"
question_index = 1
username = "manager"

[[rubric]]
kind = "relative"
value = -2
text = "wrong limit at infinity"
tags = "demo"
meta = "Student did not rearrange correctly to compute infinite limit"
question_index = 1
username = "manager"

[[rubric]]
kind = "relative"
value = -2
text = "must simplify absolute value"
tags = "demo"
meta = "Student forgot to simplify abs value before taking limit"
question_index = 1
username = "manager"


[[rubric]]
kind = "relative"
value = -1
text = "careful - minor error"
tags = "demo"
meta = "Student made small arithmetic mistake when computing limit"
question_index = 1
username = "manager"

[[rubric]]
kind = "relative"
value = -1
text = "this does not follow"
tags = "demo"
meta = "Student made logical error from one line to the next"
question_index = 1
username = "manager"

[[rubric]]
kind = "neutral"
text = "be careful"
tags = "demo"
meta = "Student made an inconsequential error."
question_index = 1
username = "manager"

[[rubric]]
kind = "neutral"
text = "hard to read"
tags = "demo"
meta = "Student handwriting is making marking hard"
question_index = 1
username = "manager"

[[rubric]]
kind = "relative"
value = 2
text = "correct derivative"
tags = "demo"
meta = "Student evaluated derivative correctly"
question_index = 2
username = "manager"

[[rubric]]
kind = "relative"
value = 1
text = "right idea, but be careful"
tags = "demo"
meta = "Student made small arithmetic mistake when computing derivative"
question_index = 2
username = "manager"

[[rubric]]
kind = "relative"
value = -2
text = "substantial error"
tags = "demo"
meta = "Student made substantial error when computing derivative"
question_index = 2
username = "manager"

[[rubric]]
kind = "relative"
value = -2
text = "not the chain rule"
tags = "demo"
meta = "Student got chain rule wrong"
question_index = 2
username = "manager"

[[rubric]]
kind = "relative"
value = -2
text = "not the product rule"
tags = "demo"
meta = "Student got product rule wrong"
question_index = 2
username = "manager"

[[rubric]]
kind = "relative"
value = -2
text = "not the quotient rule"
tags = "demo"
meta = "Student got quotient rule wrong"
question_index = 2
username = "manager"


[[rubric]]
kind = "relative"
value = -1
text = "minor error in derivative"
tags = "demo"
meta = "Student had right idea but made minor error differentiating component"
question_index = 2
username = "manager"

[[rubric]]
kind = "relative"
value = -1
text = "not derivative of log"
tags = "demo"
meta = "Student got derivative of log wrong"
question_index = 2
username = "manager"

[[rubric]]
kind = "relative"
value = -1
text = "incorrect trig derivative"
tags = "demo"
meta = "Student got derivative of trig function wrong"
question_index = 2
username = "manager"


[[rubric]]
kind = "relative"
value = -1
text = "careful - minor error"
tags = "demo"
meta = "Student made small arithmetic mistake when computing derivative"
question_index = 2
username = "manager"

[[rubric]]
kind = "relative"
value = -1
text = "this does not follow"
tags = "demo"
meta = "Student made logical error from one line to the next"
question_index = 2
username = "manager"

[[rubric]]
kind = "neutral"
text = "be careful"
tags = "demo"
meta = "Student made an inconsequential error."
question_index = 2
username = "manager"

[[rubric]]
kind = "neutral"
text = "hard to read"
tags = "demo"
meta = "Student handwriting is making marking hard"
question_index = 2
username = "manager"

[[rubric]]
kind = "relative"
value = 4
text = "Correct taylor and approx"
tags = "demo"
meta = "Student computed taylor and got right approx"
question_index = 3
username = "manager"

[[rubric]]
kind = "relative"
value = 3
text = "Correct taylor polynomial"
tags = "demo"
meta = "Student computed taylor correctly"
question_index = 3
username = "manager"

[[rubric]]
kind = "relative"
value = 1
text = "correct approximation"
tags = "demo"
meta = "Student evaluated taylor to get right approximation"
question_index = 3
username = "manager"

[[rubric]]
kind = "relative"
value = -4
text = "this is not Taylor"
tags = "demo"
meta = "Student didn't know where to start."
question_index = 3
username = "manager"

[[rubric]]
kind = "relative"
value = -3
text = "major errors in\n derivatives and taylor"
tags = "demo"
meta = "Student did something wrong building derivatives and it followed into the approx"
question_index = 3
username = "manager"


[[rubric]]
kind = "relative"
value = -2
text = "minor error in taylor and approx"
tags = "demo"
meta = "Student did something wrong building derivatives and it followed into the approx"
question_index = 3
username = "manager"

[[rubric]]
kind = "relative"
value = -1
text = "wrong way to get approximation"
tags = "demo"
meta = "Student did something weird while trying to get the approximation"
question_index = 3
username = "manager"

[[rubric]]
kind = "relative"
value = -1
text = "how does this follow"
tags = "demo"
meta = "It is hard to follow the students reasoning"
question_index = 3
username = "manager"



[[rubric]]
kind = "neutral"
text = "be careful"
tags = "demo"
meta = "Student made an inconsequential error."
question_index = 3
username = "manager"

[[rubric]]
kind = "neutral"
text = "hard to read"
tags = "demo"
meta = "Student handwriting is making marking hard"
question_index = 3
username = "manager"

[[rubric]]
kind = "neutral"
text = "layout work more carefully"
tags = "demo"
meta = "Student needs to learn how to set out their work so someone else can follow."
question_index = 3
username = "manager"

[[rubric]]
kind = "absolute"
value = 1
out_of = 3
text = "Newton's law of cooling mentioned but no diff eqn or general solution"
username = "manager"
question_index = 4
versions = "1"

[[rubric]]
kind = "absolute"
value = 1
out_of = 3
text = "Incorrect differential equation stated"
username = "manager"
question_index = 4


[[rubric]]
kind = "absolute"
value = 2
out_of = 3
text = "Differential equation formed but error in solution"
username = "manager"
question_index = 4

[[rubric]]
kind = "absolute"
value = 3
out_of = 3
text = "Differential equation formed and general solution stated"
username = "manager"
question_index = 4

[[rubric]]
kind = "absolute"
value = 3
out_of = 3
text = "Differential equation formed and solved to find general solution"
username = "manager"
question_index = 4

[[rubric]]
kind = "relative"
value = -1
out_of = 0
text = "Answer should include units\n(such as \"s\")"
username = "manager"
question_index = 4


[[rubric]]
kind = "relative"
value = 1
out_of = 0
text = "some initial progress"
meta = "The student has made some minimal progress."
username = "manager"
question_index = 4

[[rubric]]
kind = "relative"
value = 2
out_of = 0
text = "Correct set-up"
meta = "The student has set up the problem correctly."
username = "manager"
question_index = 4

[[rubric]]
kind = "relative"
value = 1
out_of = 0
text = "small algebra error"
meta = "The student has made minor algebra error"
username = "manager"
question_index = 4

[[rubric]]
kind = "relative"
value = 1
out_of = 0
text = "small arithmetic error"
meta = "The student has made minor arithmetic error"
username = "manager"
question_index = 4

[[rubric]]
kind = "neutral"
text = "be careful"
tags = "demo"
meta = "Student made an inconsequential error."
question_index = 4
username = "manager"

[[rubric]]
kind = "neutral"
text = "hard to read"
tags = "demo"
meta = "Student handwriting is making marking hard"
question_index = 4
username = "manager"

[[rubric]]
kind = "neutral"
text = "layout work more carefully"
tags = "demo"
meta = "Student needs to learn how to set out their work so someone else can follow."
question_index = 4
username = "manager"
