# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2022-2025 Colin B. Macdonald

# modified an older version of the demo to experiment with shared pages

name = "plomdemo"
longName = "Midterm Demo using Plom"

numberOfVersions = 2
numberOfPages = 6
totalMarks = 20
numberOfQuestions = 5
idPage = 1
doNotMarkPages = [2]
allowSharedPages = true

[[question]]
label = "Q1a"
pages = [3]
mark = 2

[[question]]
label = "Q1bc"
pages = [3]
mark = 3

[[question]]
label = "Q2"
pages = [4]
mark = 5

[[question]]
label = "Q3"
pages = [5, 6]
mark = 9

[[question]]
label = "Q3ex"
pages = [6]
mark = 1
