# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2024 Andrew Rechntizer
# Copyright (C) 2024 Colin B. Macdonald

[[rubric]]
kind = "relative"
value = 4
text = "Correct taylor and approx"
tags = "demo"
meta = "Student computed taylor and got right approx"
question = 3
username = "manager"

[[rubric]]
kind = "relative"
value = 3
text = "Correct taylor polynomial"
tags = "demo"
meta = "Student computed taylor correctly"
question = 3
username = "manager"

[[rubric]]
kind = "relative"
value = 1
text = "correct approximation"
tags = "demo"
meta = "Student evaluated taylor to get right approximation"
question = 3
username = "manager"

[[rubric]]
kind = "relative"
value = -4
text = "this is not Taylor"
tags = "demo"
meta = "Student didn't know where to start."
question = 3
username = "manager"

[[rubric]]
kind = "relative"
value = -3
text = "major errors in\n derivatives and taylor"
tags = "demo"
meta = "Student did something wrong building derivatives and it followed into the approx"
question = 3
username = "manager"


[[rubric]]
kind = "relative"
value = -2
text = "minor error in taylor and approx"
tags = "demo"
meta = "Student did something wrong building derivatives and it followed into the approx"
question = 3
username = "manager"

[[rubric]]
kind = "relative"
value = -1
text = "wrong way to get approximation"
tags = "demo"
meta = "Student did something weird while trying to get the approximation"
question = 3
username = "manager"

[[rubric]]
kind = "relative"
value = -1
text = "how does this follow"
tags = "demo"
meta = "It is hard to follow the students reasoning"
question = 3
username = "manager"



[[rubric]]
kind = "neutral"
text = "be careful"
tags = "demo"
meta = "Student made an inconsequential error."
question = 3
username = "manager"

[[rubric]]
kind = "neutral"
text = "hard to read"
tags = "demo"
meta = "Student handwriting is making marking hard"
question = 3
username = "manager"

[[rubric]]
kind = "neutral"
text = "layout work more carefully"
tags = "demo"
meta = "Student needs to learn how to set out their work so someone else can follow."
question = 3
username = "manager"
