# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2023 Edith Coates
# Copyright (C) 2023 Andrew Rechnitzer

test_spec = "demo"
test_sources = "demo"
prenaming_enabled = true
classlist = "demo"
num_to_produce = 70

# bundle 1
[[bundles]]
first_paper = 1
last_paper = 10
garbage_page_papers = [1, 2]
duplicate_qr_papers = [3, 4]
wrong_version_papers = [5, 6]
duplicate_page_papers = [7, 8]
scrap_page_papers = [7, 8]


# bundle 2
[[bundles]]
first_paper = 11
last_paper = 20
extra_page_papers = [19, 20]
scrap_page_papers = [19, 20]
discard_pages=[51, 54, 60, 64]


# bundle 3
[[bundles]]
first_paper = 21
last_paper = 30
scrap_page_papers = [21, 22]


# bundle 4
[[bundles]]
first_paper = 31
last_paper = 40
extra_page_papers = [31, 32]


# bundle 5
[[bundles]]
first_paper = 41
last_paper = 70


# HW bundle 1
[[hw_bundles]]
paper_number = 61
pages = [[1], [2], [], [2, 3], [3]]


# HW bundle 2
[[hw_bundles]]
paper_number = 62
pages = [[1], [1, 2], [2], [], [3]]


# HW bundle 3
[[hw_bundles]]
paper_number = 63
pages = [[1, 2], [3], []]
